find_path(EIGEN3_INCLUDE_DIR NAMES Core
	PATHS ${CONAN_INCLUDE_DIRS_EIGEN3}
	PATH_SUFFIXES Eigen
	NO_DEFAULT_PATH
)

set(EIGEN3_FOUND TRUE)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Eigen3 DEFAULT_MSG
	EIGEN3_FOUND
	EIGEN3_INCLUDE_DIR
)

set(EIGEN3_INCLUDE_DIR ${EIGEN3_INCLUDE_DIR}/..)

mark_as_advanced(EIGEN3_INCLUDE_DIR)
